apiVersion: batch/v1
kind: Job
metadata:
  name: jmeterjob
  labels:
    env: test
    jobgroup: jmeter
spec:
  parallelism: 200
  ttlSecondsAfterFinished: 60
  template:
    metadata:
      name: jmeter
      labels:
        jobgroup: jmeter      
    spec:
      tolerations:
      - key: "sku"
        operator: "Equal"
        value: "jmeter"
        effect: "NoSchedule"   
      # hostAliases:
      # - ip: "20.49.204.139"
      #   hostnames:
      #   - "www.gov.uk"
      #   - "assets.publishing.service.gov.uk"
      containers:
      - name: jmeter
        image: glasswallsolutions/cloud-qa:proxy_EKS_1.8
        imagePullPolicy: IfNotPresent
        # resources:
        #   requests:
        #     memory: "3072Mi"
        #     cpu: "1500m"
        #   limits:
        #     memory: "3072Mi"
        #     cpu: "1500m"        
        # env:
        #   # Source Minio Infromation
        #   - name: TARGET_MINIO_URL
        #     value: "http://minio.minio.svc.cluster.local:9000"
        #   - name: TARGET_MINIO_ACCESS_KEY
        #     valueFrom:
        #       secretKeyRef:
        #         name: minio-creds-secret
        #         key: accesskey
        #   - name: TARGET_MINIO_SECRET_KEY
        #     valueFrom:
        #       secretKeyRef:
        #         name: minio-creds-secret
        #         key: secretkey
        #   - name: TARGET_MINIO_BUCKET
        #     value: output
        #   # Log Level (Default to Info)
        #   - name: LOG_LEVEL
        #     value: info
        #   # Environment info
        #   - name: MY_NODE_NAME
        #     valueFrom:
        #       fieldRef:
        #         fieldPath: spec.nodeName
        #   - name: POD_NAME
        #     valueFrom:
        #       fieldRef:
        #         fieldPath: metadata.name
        #   - name: MY_POD_NAMESPACE
        #     valueFrom:
        #       fieldRef:
        #         fieldPath: metadata.namespace
        #   - name: MY_POD_IP
        #     valueFrom:
        #       fieldRef:
        #         fieldPath: status.podIP
        #   - name: MY_POD_SERVICE_ACCOUNT
        #     valueFrom:
        #       fieldRef:
        #         fieldPath: spec.serviceAccountName
          # JVM
          # - name: JVM_ARGS
          #   value: "-Xms1024m -Xmx1024m"
        #env:
        #workingDir: /mnt/workspace
        #command: [ "/bin/sh", "-c", "/mnt/workspace/jmeter.sh" ]
      #   volumeMounts:
      #   - name: jmetervol
      #     mountPath: "/usr/share/jmx"
      #     readOnly: true
      #   - name: filesvol
      #     mountPath: "/usr/share/data"
      #     readOnly: true
      # volumes:
      # - name: jmetervol
      #   secret:
      #     secretName: jmeterconf          
      # - name: filesvol
      #   secret:
      #     secretName: filesconf
      restartPolicy: Never